USE PROYECTO_WYK;

														   /*PROCEDIMIENTOS DE ACTUALIZAR*/
                                                        
														/*👮‍PROCEDIMIENTO ACTUALIZAR CARGO👮‍*/
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_CARGO
(IN P_A_ID_CARGO INT,
IN P_A_NOMBRE_CARGO VARCHAR(50),
IN P_A_ESTADO_CARGO BOOLEAN)
BEGIN
UPDATE CARGO
SET NOMBRE_CARGO=P_A_NOMBRE_CARGO,ESTADO_CARGO=P_A_ESTADO_CARGO
WHERE ID_CARGO=P_A_ID_CARGO;
END$

CALL ACTUALIZAR_CARGO(5,'HOLA',0);

SELECT*FROM CARGO;

														/*👩‍🍳PROCEDIMIENTO ACTUALIZAR EMPLEADO👨‍🍳*/
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_EMPLEADO
(
IN P_A_ID_EMPLEADO INT,
IN P_A_CC_ENPLEADO BIGINT,
IN P_A_NOMBRE_ENPLEADO VARCHAR(50),
IN P_A_RH_EMPLEADO VARCHAR (10),
IN P_A_TEL_EMPLEADO BIGINT,
IN P_A_ENAIL_EMPLEADO VARCHAR(50),
IN P_A_ID_CARGO_FK_EMPLEADO INT,
IN P_A_ESTADO_EMPLEADO BOOLEAN
)		
BEGIN
UPDATE EMPLEADO 
SET CC_ENPLEADO=P_A_CC_ENPLEADO,NOMBRE_ENPLEADO=P_A_NOMBRE_ENPLEADO,RH_EMPLEADO=P_A_RH_EMPLEADO,TEL_EMPLEADO=P_A_TEL_EMPLEADO,
ENAIL_EMPLEADO=P_A_ENAIL_EMPLEADO,ID_CARGO_FK_EMPLEADO=P_A_ID_CARGO_FK_EMPLEADO,ESTADO_EMPLEADO=P_A_ESTADO_EMPLEADO
WHERE ID_EMPLEADO=P_A_ID_EMPLEADO;
END $	

CALL ACTUALIZAR_EMPLEADO(5,1005005005,'Sebastian Pinto','O+',3015202833,'juanpintow@gmaiol.com',5,0);

SELECT*FROM EMPLEADO;	

														/*👦PROCEDIMIENTO ACTUALIZAR CLIENTE👦*/	
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_CLIENTE
(
IN P_A_ID_CLIENTE INT,
IN P_A_NUM_DOCUMENTO_CLIENTE BIGINT,
IN P_A_TIPO_DOCUMENTO_CLIENTE ENUM ('TI','CC','CE'),
IN P_A_NOMBRE_CLIENTE VARCHAR(50),
IN P_A_TEL_CLIENTE BIGINT,
IN P_A_EMAIL_CLIENTE VARCHAR(50),
IN P_A_ID_EMPLEADO_FK_CLIENTE INT,
IN P_A_ESTADO_CLIENTE BOOLEAN
)   
BEGIN
UPDATE CLIENTE
SET NUM_DOCUMENTO_CLIENTE=P_A_NUM_DOCUMENTO_CLIENTE,TIPO_DOCUMENTO_CLIENTE=P_A_TIPO_DOCUMENTO_CLIENTE,NOMBRE_CLIENTE=P_A_NOMBRE_CLIENTE,TEL_CLIENTE=P_A_TEL_CLIENTE,
EMAIL_CLIENTE=P_A_EMAIL_CLIENTE,ID_EMPLEADO_FK_CLIENTE=P_A_ID_EMPLEADO_FK_CLIENTE,ESTADO_CLIENTE=P_A_ESTADO_CLIENTE
WHERE ID_CLIENTE=P_A_ID_CLIENTE;
END $   

CALL ACTUALIZAR_CLIENTE (5,1002001002,'TI','Yerik Hurtado',3132563434,'hurtadoyerik@gmail.com',5,0);

SELECT*FROM CLIENTE; 

														/*🤴PROCEDIMIENTO ACTUALIZAR USUARIO👸*/  
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_USUARIO
(
IN P_A_ID_USUARIO INT,
IN P_A_NOMBRE_USUARIO VARCHAR(50),
IN P_A_CONTRASEÑA_USUARIO VARCHAR(50),
IN P_A_FECHA_REGISTRO DATETIME,
IN P_A_FECHA_ULTIMA_SESION DATETIME,
IN P_A_ESTADO_USUARIO BOOLEAN
)
BEGIN
UPDATE USUARIO
SET NOMBRE_USUARIO=P_A_NOMBRE_USUARIO,CONTRASEÑA_USUARIO=P_A_CONTRASEÑA_USUARIO,FECHA_REGISTRO=P_A_FECHA_REGISTRO,
FECHA_ULTIMA_SESION=P_A_FECHA_ULTIMA_SESION,ESTADO_USUARIO=P_A_ESTADO_USUARIO
WHERE ID_USUARIO=P_A_ID_USUARIO;
END $     

CALL ACTUALIZAR_USUARIO (9,'sebas.cajero','juan040205', NOW(), NOW(), 0);

SELECT*FROM USUARIO;

														/*🤴PROCEDIMIENTO ACTUALIZAR USUARIO EMPLEADO👸*/ 
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_USUARIO_EMPLEADO
(
IN P_A_ID_USUARIO INT,
IN P_A_ID_EMPLEADO INT,
IN P_A_TIPO_ACCESO ENUM('EMPLEADO','ADMININSTRADOR')
)	
BEGIN
UPDATE USUARIO_EMPLEADO
SET ID_EMPLEADO=P_A_ID_EMPLEADO,TIPO_ACCESO=P_A_TIPO_ACCESO
WHERE ID_USUARIO=P_A_ID_USUARIO;
END $	

CALL ACTUALIZAR_USUARIO_EMPLEADO(9,5,'ADMININSTRADOR');

SELECT*FROM USUARIO_EMPLEADO;

														/*🤴PROCEDIMIENTO ACTUALIZAR USUARIO CLIENTE👸*/
                                                        
													

									
			

									