USE PROYECTO_WYK;

CREATE VIEW VISTA_CARGO AS
SELECT ID_CARGO, NOMBRE_CARGO, ESTADO_CARGO
FROM CARGO;

CREATE VIEW V_EMPLEADO AS
SELECT E.ID_EMPLEADO, E.CC_ENPLEADO, E.NOMBRE_ENPLEADO, E.RH_EMPLEADO,
       E.TEL_EMPLEADO, E.ENAIL_EMPLEADO, C.NOMBRE_CARGO, E.ESTADO_EMPLEADO
FROM EMPLEADO E
JOIN CARGO C ON E.ID_CARGO_FK_EMPLEADO = C.ID_CARGO;




