USE PROYECTO_WYK;

CREATE VIEW VISTA_CARGO AS
SELECT ID_CARGO, NOMBRE_CARGO, ESTADO_CARGO
FROM CARGO;

CREATE VIEW VISTA_EMPLEADO AS
SELECT E.ID_EMPLEADO, E.CC_ENPLEADO, E.NOMBRE_ENPLEADO, E.RH_EMPLEADO,
       E.TEL_EMPLEADO, E.ENAIL_EMPLEADO, C.NOMBRE_CARGO, E.ESTADO_EMPLEADO
FROM EMPLEADO E
JOIN CARGO C ON E.ID_CARGO_FK_EMPLEADO = C.ID_CARGO;

CREATE VIEW VISTA_CLIENTE AS
SELECT C.ID_CLIENTE, C.NUM_DOCUMENTO_CLIENTE, C.TIPO_DOCUMENTO_CLIENTE,
       C.NOMBRE_CLIENTE, C.TEL_CLIENTE, C.EMAIL_CLIENTE,
       E.NOMBRE_ENPLEADO AS ASESOR, C.ESTADO_CLIENTE
FROM CLIENTE C
JOIN EMPLEADO E ON C.ID_EMPLEADO_FK_CLIENTE = E.ID_EMPLEADO;

CREATE VIEW VISTA_USUARIO AS
SELECT U.ID_USUARIO, U.NOMBRE_USUARIO, U.FECHA_REGISTRO, U.FECHA_ULTIMA_SESION, 
       U.ESTADO_USUARIO,
       COALESCE(UE.TIPO_ACCESO, 'CLIENTE') AS TIPO_USUARIO
FROM USUARIO U
LEFT JOIN USUARIO_EMPLEADO UE ON U.ID_USUARIO = UE.ID_USUARIO;

CREATE VIEW VISTA_PEDIDO AS
SELECT P.ID_PEDIDO, P.FECHA_HORA_PEDIDO, P.NUMERO_MESA, 
       E.NOMBRE_ENPLEADO AS ATENDIDO_POR, 
       C.NOMBRE_CLIENTE AS CLIENTE,
       P.ESTADO_PEDIDO
FROM PEDIDO P
JOIN EMPLEADO E ON P.ID_EMPLEADO_FK_PEDIDO = E.ID_EMPLEADO
JOIN CLIENTE C ON P.ID_CLIENTE_FK_PEDIDO = C.ID_CLIENTE;

CREATE VIEW VISTA_PRODUCTO AS
SELECT ID_PRODUCTO, NOMBRE_PRODUCTO, VALOR_UNITARIO_PRODUCTO, 
       CANT_MINI_PRODUCTO, CANT_MAX_PRODUCTO, CANT_EXIST_PRODUCTO,
       FECHA_VENCIMIENTO_PRODUCTO, TIPO_PRODUCTO_GERENERAL, TIPO_PRODUCTO_ESPECIFICO,
       MARCA_PRODUCTO, ESTADO_PRODUCTO
FROM PRODUCTO;

CREATE VIEW VISTA_DETALLE_PEDIDO AS
SELECT D.ID_DETALLE_PEDIDO, D.DESCRIPCION_DETALLE_PEDIDO,
       P.NOMBRE_PRODUCTO, DP.FECHA_HORA_PEDIDO, D.DETALLE_PEDIDO_PRODUCTO
FROM DETALLE_PEDIDO D
JOIN PRODUCTO P ON D.ID_PRODUCTO_FK_DETALLE_PEDIDO = P.ID_PRODUCTO
JOIN PEDIDO DP ON D.ID_PEDIDO_FK_DETALLE_PEDIDO = DP.ID_PEDIDO;

CREATE VIEW VISTA_FACTURA_VENTA AS
SELECT F.ID_FACTURA_VENTA, F.TOTAL_FACTURA_VENTA, F.FECHA_HORA_FACTURA_VENTA,
       F.DESCRIPCION_FACTURA_VENTA, E.NOMBRE_ENPLEADO AS VENDEDOR,
       C.NOMBRE_CLIENTE AS CLIENTE, P.ID_PEDIDO,
       F.ESTADO_FACTURA_VENTA
FROM FACTURA_VENTA F
JOIN EMPLEADO E ON F.ID_EMPLEADO_FK_FACTURA_VENTA = E.ID_EMPLEADO
JOIN CLIENTE C ON F.ID_CLIENTE_FK_FACTURA_VENTA = C.ID_CLIENTE
JOIN PEDIDO P ON F.ID_PEDIDO_FK_FACTURA_VENTA = P.ID_PEDIDO;








