USE PROYECTO_WYK;

CREATE VIEW VISTA_CARGO AS
SELECT ID_CARGO, NOMBRE_CARGO, ESTADO_CARGO
FROM CARGO;

CREATE VIEW VISTA_EMPLEADO AS
SELECT E.ID_EMPLEADO, E.CC_ENPLEADO, E.NOMBRE_ENPLEADO, E.RH_EMPLEADO,
       E.TEL_EMPLEADO, E.ENAIL_EMPLEADO, C.NOMBRE_CARGO, E.ESTADO_EMPLEADO
FROM EMPLEADO E
JOIN CARGO C ON E.ID_CARGO_FK_EMPLEADO = C.ID_CARGO;

CREATE VIEW VISTA_CLIENTE AS
SELECT C.ID_CLIENTE, C.NUM_DOCUMENTO_CLIENTE, C.TIPO_DOCUMENTO_CLIENTE,
       C.NOMBRE_CLIENTE, C.TEL_CLIENTE, C.EMAIL_CLIENTE,
       E.NOMBRE_ENPLEADO AS ASESOR, C.ESTADO_CLIENTE
FROM CLIENTE C
JOIN EMPLEADO E ON C.ID_EMPLEADO_FK_CLIENTE = E.ID_EMPLEADO;

CREATE VIEW VISTA_USUARIO AS
SELECT U.ID_USUARIO, U.NOMBRE_USUARIO, U.FECHA_REGISTRO, U.FECHA_ULTIMA_SESION, 
       U.ESTADO_USUARIO,
       COALESCE(UE.TIPO_ACCESO, 'CLIENTE') AS TIPO_USUARIO
FROM USUARIO U
LEFT JOIN USUARIO_EMPLEADO UE ON U.ID_USUARIO = UE.ID_USUARIO;

CREATE VIEW VISTA_PEDIDO AS
SELECT P.ID_PEDIDO, P.FECHA_HORA_PEDIDO, P.NUMERO_MESA, 
       E.NOMBRE_ENPLEADO AS ATENDIDO_POR, 
       C.NOMBRE_CLIENTE AS CLIENTE,
       P.ESTADO_PEDIDO
FROM PEDIDO P
JOIN EMPLEADO E ON P.ID_EMPLEADO_FK_PEDIDO = E.ID_EMPLEADO
JOIN CLIENTE C ON P.ID_CLIENTE_FK_PEDIDO = C.ID_CLIENTE;







