CREATE DATABASE PROYECTO_WYK;
USE PROYECTO_WYK;

CREATE TABLE CARGO
(
    ID_CARGO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE_CARGO VARCHAR(50) NOT NULL,
    ESTADO_CARGO BOOLEAN NOT NULL
);

CREATE TABLE EMPLEADO
(
    ID_EMPLEADO  INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CC_ENPLEADO BIGINT UNIQUE NOT NULL,
    NOMBRE_ENPLEADO VARCHAR(50) NOT NULL,
    RH_EMPLEADO VARCHAR(10) NOT NULL,
    TEL_EMPLEADO BIGINT NOT NULL,
    ENAIL_EMPLEADO VARCHAR(50) NOT NULL,
    ID_CARGO_FK_EMPLEADO INT NOT NULL,
    CONSTRAINT ID_CARGO_FK_EMPLEADO FOREIGN KEY (ID_CARGO_FK_EMPLEADO) REFERENCES CARGO (ID_CARGO),
    ESTADO_EMPLEADO BOOLEAN NOT NULL
);

CREATE TABLE CLIENTE 
(
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NUM_DOCUMENTO_CLIENTE BIGINT UNIQUE NOT NULL,
    TIPO_DOCUMENTO_CLIENTE ENUM ('TI','CC','CE') NOT NULL,
    NOMBRE_CLIENTE VARCHAR(50) NOT NULL,
    TEL_CLIENTE BIGINT NOT NULL,
    EMAIL_CLIENTE VARCHAR(50) NOT NULL,
    ID_EMPLEADO_FK_CLIENTE INT NOT NULL,
    CONSTRAINT ID_EMPLEADO_FK_CLIENTE FOREIGN KEY (ID_EMPLEADO_FK_CLIENTE) REFERENCES EMPLEADO (ID_EMPLEADO),
    ESTADO_CLIENTE BOOLEAN NOT NULL
);

CREATE TABLE USUARIO 
(
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE_USUARIO VARCHAR (50) UNIQUE NOT NULL,
    CONTRASEÑA_USUARIO VARCHAR (150) NOT NULL,
    FECHA_REGISTRO DATETIME NOT NULL,
    FECHA_ULTIMA_SESION DATETIME NOT NULL,
    ESTADO_USUARIO BOOLEAN NOT NULL
);

CREATE TABLE USUARIO_EMPLEADO (
    ID_USUARIO INT PRIMARY KEY,
    ID_EMPLEADO INT UNIQUE NOT NULL,
    TIPO_ACCESO ENUM('EMPLEADO','ADMININSTRADOR') NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE USUARIO_CLIENTE (
    ID_USUARIO INT PRIMARY KEY,
    ID_CLIENTE INT UNIQUE NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE PEDIDO 
(
	ID_PEDIDO BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	FECHA_HORA_PEDIDO DATETIME NOT NULL,
	NUMERO_MESA INT NOT NULL,
	ID_EMPLEADO_FK_PEDIDO INT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_PEDIDO FOREIGN KEY (ID_EMPLEADO_FK_PEDIDO) REFERENCES EMPLEADO (ID_EMPLEADO),
	ID_CLIENTE_FK_PEDIDO INT NOT NULL,
	CONSTRAINT ID_CLIENTE_FK_PEDIDO FOREIGN KEY (ID_CLIENTE_FK_PEDIDO) REFERENCES CLIENTE (ID_CLIENTE),
	ESTADO_PEDIDO ENUM('PENDIENTE','EN PREPARACION','ENTREGADO','CANCELADO') NOT NULL
);

CREATE TABLE PRODUCTO
(
	ID_PRODUCTO BIGINT PRIMARY KEY NOT NULL,
	NOMBRE_PRODUCTO VARCHAR(50) UNIQUE NOT NULL,
	VALOR_UNITARIO_PRODUCTO BIGINT NOT NULL,
	CANT_MINI_PRODUCTO BIGINT NOT NULL,
	CANT_MAX_PRODUCTO BIGINT NOT NULL,
	CANT_EXIST_PRODUCTO BIGINT NOT NULL,
	FECHA_VENCIMIENTO_PRODUCTO DATE NOT NULL,
	TIPO_PRODUCTO_GERENERAL ENUM('PANADERIA','PASTELERIA','VIBERES') NOT NULL,
	TIPO_PRODUCTO_ESPECIFICO VARCHAR(50) NOT NULL,
	MARCA_PRODUCTO VARCHAR(50) NOT NULL,
	ID_EMPLEADO_FK_PRODUCTO INT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_PRODUCTO FOREIGN KEY (ID_EMPLEADO_FK_PRODUCTO) REFERENCES EMPLEADO (ID_EMPLEADO),
	ESTADO_PRODUCTO BOOLEAN NOT NULL
);

CREATE TABLE DETALLE_PEDIDO
(
	ID_DETALLE_PEDIDO INT PRIMARY KEY NOT NULL,
	DESCRIPCION_DETALLE_PEDIDO VARCHAR(200) NOT NULL,
	ID_PEDIDO_FK_DETALLE_PEDIDO BIGINT NOT NULL,
	CONSTRAINT ID_PEDIDO_FK_DETALLE_PEDIDO FOREIGN KEY (ID_PEDIDO_FK_DETALLE_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
	ID_PRODUCTO_FK_DETALLE_PEDIDO BIGINT NOT NULL,
	CONSTRAINT ID_PRODUCTO_FK_DETALLE_PEDIDO FOREIGN KEY (ID_PRODUCTO_FK_DETALLE_PEDIDO) REFERENCES PRODUCTO (ID_PRODUCTO),
	DETALLE_PEDIDO_PRODUCTO BOOLEAN NOT NULL
);

CREATE TABLE FACTURA_VENTA
(
	ID_FACTURA_VENTA BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	TOTAL_FACTURA_VENTA BIGINT NOT NULL,
	FECHA_HORA_FCATURA_VENTA DATETIME NOT NULL,
	DESCRIPCION_FACTURA_VENTA VARCHAR(200) NOT NULL,
	ID_EMPLEADO_FK_FACTURA_VENTA INT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_FACTURA_VENTA FOREIGN KEY (ID_EMPLEADO_FK_FACTURA_VENTA) REFERENCES EMPLEADO (ID_EMPLEADO),
	ID_PEDIDO_FK_FACTURA_VENTA BIGINT NOT NULL,
	CONSTRAINT ID_PEDIDO_FK_FACTURA_VENTA FOREIGN KEY (ID_PEDIDO_FK_FACTURA_VENTA) REFERENCES PEDIDO (ID_PEDIDO),
	ID_CLIENTE_FK_FACTURA_VENTA INT NOT NULL,
	CONSTRAINT ID_CLIENTE_FK_FACTURA_VENTA FOREIGN KEY (ID_CLIENTE_FK_FACTURA_VENTA) REFERENCES CLIENTE (ID_CLIENTE),
	ESTADO_FACTURA_VENTA ENUM('PENDIENTE','PAGADA','CANCELADA') NOT NULL
);

CREATE TABLE DETALLE_VENTA_PRODUCTO
(
	ID_DETALLE_VENTA_PRODUCTO INT PRIMARY KEY NOT NULL,
	CANTIDAD_PRODUCTO_VENDIDO BIGINT NOT NULL,
	SUB_TOTAL_PRODUCTO_VENDIDO BIGINT NOT NULL,
	ID_FACTURA_VENTA_FK_DETALLE_VENTA_PRODUCTO BIGINT NOT NULL,
	CONSTRAINT ID_FACTURA_VENTA_FK_DETALLE_VENTA_PRODUCTO FOREIGN KEY (ID_FACTURA_VENTA_FK_DETALLE_VENTA_PRODUCTO) REFERENCES FACTURA_VENTA (ID_FACTURA_VENTA),
	ID_PRODUCTO_FK_DETALLE_FACTURA_VENTA BIGINT NOT NULL,
	CONSTRAINT ID_PRODUCTO_FK_DETALLE_FACTURA_VENTA FOREIGN KEY (ID_PRODUCTO_FK_DETALLE_FACTURA_VENTA) REFERENCES PRODUCTO (ID_PRODUCTO),
	ESTADO_DETALLLE_VENTA_PRODUCTO BOOLEAN NOT NULL
);

CREATE TABLE PROVEEDOR 
(
	ID_PROVEEDOR INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CC_PROVEEDOR BIGINT UNIQUE NOT NULL,
	NOMBRE_PROVEEDOR VARCHAR (50) NOT NULL,
	TEL_PROVEEDOR BIGINT NOT NULL,
	EMAIL_PROVEEDOR VARCHAR (50) NOT NULL,
	ID_EMPLEADO_FK_PROVEEDOR INT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_PROVEEDOR FOREIGN KEY (ID_EMPLEADO_FK_PROVEEDOR) REFERENCES EMPLEADO (ID_EMPLEADO),
	ESTADO_PROVEEDOR BOOLEAN NOT NULL
);

CREATE TABLE MATERIA_PRIMA
(
	ID_MATERIA_PRIMA BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOMBRE_MATERIA_PRIMA VARCHAR (50) NOT NULL,
	FECHA_VENCIMIENTO_MATERIA_PRIMA DATE NOT NULL,
	TIPO_DE_MEDIDA VARCHAR(50) NOT NULL,
	CANTIDAD_MINI_MATERIA_PRIMA BIGINT NOT NULL,
	CANTIDAD_MAX_MATERIA_PRIMA BIGINT NOT NULL,
	CANTIDAD_EXIST_MATERIA_PRIMA BIGINT NOT NULL,
	MARCA_MATERIA_PRIMA VARCHAR(50) NOT NULL,
	PRESENTACION_MATERIA_PRIMA VARCHAR (50) NOT NULL,
	DESCRIPCION_MATERIA_PRIMA VARCHAR(200) NOT NULL,
	ID_EMPLEADO_FK_MATERIA_PRIMA INT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_MATERIA_PRIMA FOREIGN KEY (ID_EMPLEADO_FK_MATERIA_PRIMA) REFERENCES EMPLEADO (ID_EMPLEADO),
	ESTADO_MATERIA_PRIMA BOOLEAN NOT NULL
);

CREATE TABLE FACTURA_COMPRA
(
	ID_FACTURA_COMPRA BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	TOTAL_FACTURA_COMPRA BIGINT NOT NULL,
	FECHA_HORA_FACTURA_COMPRA DATETIME NOT NULL,
	DESCRIPCION_FACTURA_COMPRA VARCHAR (200) NOT NULL,
	ID_EMPLEADO_FK_FACTURA_COMPRA INT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_FACTURA_COMPRA FOREIGN KEY (ID_EMPLEADO_FK_FACTURA_COMPRA) REFERENCES EMPLEADO (ID_EMPLEADO),
	ID_PROOVEEDOR_FK_FACTURA_COMPRA INT NOT NULL,
	CONSTRAINT ID_PROOVEEDOR_FK_FACTURA_COMPRA FOREIGN KEY (ID_PROOVEEDOR_FK_FACTURA_COMPRA) REFERENCES PROVEEDOR (ID_PROVEEDOR),
	ESTADO_FACTURA_COMPRA ENUM('PENDIENTE','PAGADA','CANCELADA') NOT NULL
);

CREATE TABLE DETALLE_FACTURA_COMPRA_MATERIA_PRIMA
(
	ID_DETALLE_FAC_MAT_PRIM INT PRIMARY KEY NOT NULL,
	CANTIDAD_MATERIA_PRIMA_COMPRADA BIGINT NOT NULL,
	SUB_TOTAL_MATERI_PRIMA_COMPRADA BIGINT NOT NULL,
	ID_FACTURA_COMPRA_FK_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA BIGINT NOT NULL,
	CONSTRAINT ID_FACTURA_COMPRA_FK_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA FOREIGN KEY (ID_FACTURA_COMPRA_FK_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA) 
	REFERENCES FACTURA_COMPRA (ID_FACTURA_COMPRA),
	ID_MATERIA_PRIMA_FK_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA BIGINT NOT NULL,
	CONSTRAINT ID_MATERIA_PRIMA_FK_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA FOREIGN KEY (ID_MATERIA_PRIMA_FK_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA) 
	REFERENCES MATERIA_PRIMA (ID_MATERIA_PRIMA),
	ESTADO_DETAllE_COMPRA_MATERIA_PRIMA BOOLEAN NOT NULL
);

CREATE TABLE DETALLE_COMPRA_PRODUCTO
(
	ID_DETALLE_COMPRA_PRODUCTO INT PRIMARY KEY NOT NULL,
	CANTIDAD_PRODUCTO_COMPRADO BIGINT NOT NULL,
	SUB_TOTAL_PRODUCTO_COMPRADO BIGINT NOT NULL,
	ID_FACTURA_COMPRA_FK_DETALLE_COMPRA_PRODUCTO BIGINT NOT NULL,
	CONSTRAINT ID_FACTURA_COMPRA_FK_DETALLE_COMPRA_PRODUCTO FOREIGN KEY (ID_FACTURA_COMPRA_FK_DETALLE_COMPRA_PRODUCTO) REFERENCES FACTURA_COMPRA (ID_FACTURA_COMPRA),
	ID_PRODUCTO_FK_DETALLE_COMPRA_PRODUCTO BIGINT NOT NULL,
	CONSTRAINT ID_PRODUCTO_FK_DETALLE_COMPRA_PRODUCTO FOREIGN KEY (ID_PRODUCTO_FK_DETALLE_COMPRA_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
	ESTADO_DETALLE_COMPRA_PRODUCTO BOOLEAN NOT NULL
);

CREATE TABLE PRODUCCION
(
	ID_PRODUCCION BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOMBRE_PRODUCCION VARCHAR (50) NOT NULL,
	CANT_PRODUCCION BIGINT NOT NULL,
	DESCRIPCION_PRODUCCION VARCHAR(200) NOT NULL,
	MATERIA_PRIMA_GASTADA BIGINT NOT NULL,
	ID_MATERIA_PRIMA_FK_PRODUCCION BIGINT NOT NULL,
	CONSTRAINT ID_MATERIA_PRIMA_FK_PRODUCCION FOREIGN KEY (ID_MATERIA_PRIMA_FK_PRODUCCION) REFERENCES MATERIA_PRIMA (ID_MATERIA_PRIMA),
	ID_PRODUCTO_FK_MATERIA_PRIMA BIGINT NOT NULL,
	CONSTRAINT ID_PRODUCTO_FK_MATERIA_PRIMA FOREIGN KEY (ID_PRODUCTO_FK_MATERIA_PRIMA) REFERENCES PRODUCTO (ID_PRODUCTO),
	ID_EMPLEADO_FK_PRODUCCION INT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_PRODUCCION FOREIGN KEY (ID_EMPLEADO_FK_PRODUCCION) REFERENCES EMPLEADO (ID_EMPLEADO),
	ESTADO_PRODUCCION BOOLEAN NOT NULL
);